### ISSUE TITLE
func插件：在表达式里调用函数时崩溃

### ISSUE THREAD

**Issue by Lazy-Rabbit-2001** [defisym/OpenFusionExamples#1]
rt，就是这样，求修复

**Comment by defisym** [comment]
提供的信息太少，不知道你具体的使用情况，没办法定位问题。我这里测试的时候是正常的。
在用表达式里调用的时候必须要提供一个返回值，没有返回值会抛异常。
另外，参数编号是从零开始的，越界了也会抛异常。
