### ISSUE TITLE
FFMpeg Bugs

### ISSUE THREAD

**Issue by SelfReflection31** [defisym/OpenFusionExamples#10]
was playing and found bugs

- WEBM files do not load
- some mp4 videos do not work some does
- Set Poistion is odd. quickly setting positions freezes the video 
- 1080 example is needing another extension for it to be open properly. 
- high resolution and large mp4 files freezes

**Comment by defisym** [comment]
> WEBM files do not load

please provide the demo video.
just download a webm video file from youtube and works fine here.

> some mp4 videos do not work some does

please provide the demo video.
MP4 is a container and some codec formats may not supported by LGPL version of FFMpeg.

> Set Poistion is odd. quickly setting positions freezes the video

works fine here:
FF & rewind by pressing keyboard.

https://user-images.githubusercontent.com/55148235/190062313-9e266c45-1ed4-4299-bd42-e94994a8b6c1.mp4

IDK how fast you are, if use an always condition then it's correct to freeze:

1. MP4 need multiple packets to decode one frame, it needs about 50ms to re-construct the stream.
2. Display won't update if video goes before audio

so you may suck into the situtation: 

1. jump to new position, but audio buffer also have a few data to play, so it didn't ask to decode new packets immediately
2. video frame are decoded firstly, so it's faster than audio
3. before it's synced you jump to next position

> 1080 example is needing another extension for it to be open properly.

this example contains a frame to test grab video frame, that expression will return a pointer to cSurface, and need the following object to read:
https://github.com/defisym/OpenFusionExamples/tree/master/Extensions/NeoPic
Surface also has a 'load reference' action to load pointers but IDK if it is build as /MT or /MD, or to say use the same heap.

> high resolution and large mp4 files freezes

currently it has a bug that surface didn't update if new video's resolution is different to current one's, don't know if it is the case.
and make sure do not read a normal file in encrypted way or do the contrast.
FFmpeg only reads the beginning header of file then stream it so the size doesn't matter.

**Comment by SelfReflection31** [comment]
[videos.zip](https://github.com/defisym/OpenFusionExamples/files/9566556/videos.zip)

zip pack of two videos used in example video below

https://user-images.githubusercontent.com/113463662/190162983-8ddf4df1-83ca-4c36-ace6-b3419c545e38.mp4

was able to get webm to play video1 but not video2 it same video just lower quality.
In video shown the delay when setting position and crash with video2 at end

cannot understand if set position is seconds or milliseconds so used both.

**Comment by defisym** [comment]
> was able to get webm to play video1 but not video2 it same video just lower quality.

>>     * For video the linesizes should be multiples of the CPUs alignment
>>     * preference, this is 16 or 32 for modern desktop CPUs.
>>     * Some code requires such alignment other code can be slower without
>>     * correct alignment, for yet other it makes no difference.
>>     *
>>     * @note The linesize may be larger than the size of usable data -- there
>>     * may be extra padding present for performance reasons.

it's not about the format but the extra padding. Didn't take that into account before.
also modified a bit for the negative case.

![image](https://user-images.githubusercontent.com/55148235/190187762-5adbdf1c-0377-47ad-8b5c-bcc31760baea.png)

> In video shown the delay when setting position 

reset sync then it works, mainly due to incorrect waiting.
note that currently seek is using flag `AVSEEK_FLAG_BACKWARD | AVSEEK_FLAG_FRAME`, so may not jump to the exact time you seek for.

> cannot understand if set position is seconds or milliseconds so used both.

milliseconds

```C++
	int msRaw = (int)CNC_GetIntParameter(rdPtr);

	if (!rdPtr->bOpen) {
		return 0;
	}

	// add protection for minus position
	msRaw = msRaw < 0 ? 0 : msRaw;

	size_t ms = (size_t)msRaw;

	rdPtr->pFFMpeg->set_videoPosition(ms);

	if (!rdPtr->bPlay) {
		BlitVideoFrame(rdPtr, ms, rdPtr->pMemSf);
	}

	ReDisplay(rdPtr);

	return 0;
```

the input will be convert to the frame number:

```C++
		auto protectedTimeInMs = min(totalTimeInMs, max(0, ms));
		auto protectedTime = protectedTimeInMs / 1000;
		auto protectedFrame = protectedTime / decimalRational;

		return (int64_t)(protectedFrame);
```

**Comment by SelfReflection31** [comment]
> note that currently seek is using flag AVSEEK_FLAG_BACKWARD | AVSEEK_FLAG_FRAME, so may not jump to the exact time you seek for.

Will this be changed to get exact seek or frame sometime in the future? 

also noticing that webm has alpha channel. will there be option to have it used?

**Comment by defisym** [comment]
> Will this be changed to get exact seek or frame sometime in the future?

Sure, add extra flag options is quite easy.

> also noticing that webm has alpha channel. will there be option to have it used?

Didn't take aplha channel into account, it's ignored when copying to fusion. Will be added.

**Comment by defisym** [comment]
> Will this be changed to get exact seek or frame sometime in the future?

New action allows you to set seek flags: 

```C++
#define AVSEEK_FLAG_BACKWARD 1 ///< seek backward
#define AVSEEK_FLAG_BYTE     2 ///< seeking based on position in bytes
#define AVSEEK_FLAG_ANY      4 ///< seek to any frame, even non-keyframes
#define AVSEEK_FLAG_FRAME    8 ///< seeking based on frame number
```

defaultly will use `av_seek_frame`, if flag <= 0 then will use `avformat_seek_file` instead:

```C++
		response = seekFlags > 0
			? av_seek_frame(pFormatContext, stream_index
				, seek_target
				, seekFlags)
			: avformat_seek_file(pFormatContext, stream_index
				, seek_target, seek_target, seek_target
				, -1 * seekFlags);
```

> also noticing that webm has alpha channel. will there be option to have it used?

accroding to this, alpha support for webm is difficult to add:
https://ffmpeg.org/pipermail/ffmpeg-user/2014-January/019283.html

but other formats with alpha support like mov works in the latest build:
![image](https://user-images.githubusercontent.com/55148235/190584789-2001ca40-2b27-4d66-9182-e09589a1b63f.png)

you can see the fat pikachu under video.

**Comment by SelfReflection31** [comment]
mov alpha does work! bit sad that webm is difficult to implement... it had good low file size compared to mov.

still set position is odd verse directshow..

https://user-images.githubusercontent.com/113463662/190686851-eb211597-5e1c-41ed-9863-0ede49727c3e.mp4

**Comment by defisym** [comment]
Is video 1 the same one you provided before? I'll check it later. Might because of the precision lose when calculating frame number based on millisecond time.
Don't know if set the `AVSEEK_FLAG_ANY` flag can fix this as FFMpeg uses key frame by default.

**Comment by SelfReflection31** [comment]
yes. 
was testing around on mp4s too and found that it still does not set to exact frame or second.

**Comment by defisym** [comment]
It's due to some file types, including webm, do not define the duration per-stream, so the total duration returns a negative value, or `AV_NOPTS_VALUE` to be more specific. So, the duration based returns a negative value, then the jump target is set to zero due to the protection code to make sure it's smaller than duration.

```C++
		// protection
		ms = min(max(ms, 0), get_videoDuration());
		response = seekFrame(pFormatContext, steam_index, ms);
```

use the duration defined in AVFormatContext fix it.

```C++
......

		if (pVideoStream->duration != AV_NOPTS_VALUE) {
			totalDuration = pVideoStream->duration;

			rational = pVideoStream->time_base;
		}
		else {
			totalDuration = pFormatContext->duration;

			rational = time_base_q;
		}

......
```

**Comment by SelfReflection31** [comment]
I see now.. 
heres another example just in case
[segment_example.zip](https://github.com/defisym/OpenFusionExamples/files/9592133/segment_example.zip)

**Comment by defisym** [comment]
latest version implemented accurate seek, a check box in object properties.
Please use it with `AVSEEK_FLAG_BACKWARD`. It will first jump to the closest key frame first then decode frames until it reaches the given time stamp.
As I said above, it do have a performance impact, especially for high quality video with high compression rate, which means it needs to decode more packet to get the target frame, and it's time consuming.

**Comment by SelfReflection31** [comment]
ok that works.. I'm still confused on to use the accurate seeking method. there should be an example mfa. 
I also found problem, if rendering a video with no audio codec. it causes the extension to hang/lag a few milliseconds after setting position. maybe a checkbox to skip audio?

**Comment by defisym** [comment]
> I'm still confused on to use the accurate seeking method

check it in object properties, then the default set position without flags should work.
or add AVSEEK_FLAG_BACKWARD flag in the one that ask for flags.

> there should be an example mfa.

after features are stable and I have some time I'll document it.

> I also found problem, if rendering a video with no audio codec. it causes the extension to hang/lag a few milliseconds after setting position. maybe a checkbox to skip audio?

If the video has no audio, then an external timer is used for sync. Didn't take seeking into account, timer will be reset to current time (timer will save the time you start playing, and compare to current time & current pts), which works when looping but causes delay when seeking, as extension will think video is faster than clock and wait.

latest version will use an estimate timer after seeking based on target pts.

**Comment by defisym** [comment]
Hi, if no new issues I will close this issue as solved. Thanks for your help of polishing this extension.
