### ISSUE TITLE
Feature requests for the NeoPic object

### ISSUE THREAD

**Issue by PiKeyAr** [defisym/OpenFusionExamples#14]
Thank you for all the excellent work on this repo, and for the NeoPic object which I found of great use in my projects. I'd like to ask if you would consider implementing two features in the NeoPic extension that would be useful for background and animation systems built on this object.

**Describe the solution you'd like**
1. "Flip horizontally" and "Flip vertically" flags that can be toggled via an action. When the flag is on, the object's display surface is flipped horizontally and/or vertically until the flag is cleared. This would be helpful for character animations in side-scrolling games.
2. An action similar to "Display > Transform > Stretch" but the image would be repeated rather than stretched, like in Quick Backdrop's Motif mode. This would be helpful for tiling backgrounds.

**Describe alternatives you've considered**
1. Flipping can be done via a shader but having a built-in option would free up the shader to be used for other effects on the object. H+V flipping can be done by rotating by 180 degrees, but this does not allow to flip just horizontally or just vertically.
2. Tiling can be done by making multiple instances of the object with the same image, or by loading an already tiled large image into the object. A built-in option would allow for cleaner implementation.

It would be great if you could consider these for a new update. Thanks a lot!

**Comment by defisym** [comment]
> "Flip horizontally" and "Flip vertically"

negative scale was implemented at start but soon removed due to performance issue, maybe I can cache flipped surfaces, but that requires 4x memory usage in worst cases.

> Quick Backdrop's Motif mode.

render to an offscreen bitmap then convert it to hwa surface for display, which is slow when changing tiles and size, as it need to be re-generated.

I'll try to add these and see if the performance hit is important or not.

---------------------------

off topic:

![image](https://user-images.githubusercontent.com/55148235/211048071-6d95ed5b-1c01-439c-8c54-7efe7c42d89a.png)

your avatar reminds me the old time watching Keroro Gunso......

**Comment by defisym** [comment]
Hi, the latest push contains those new features, please check it.

![image](https://user-images.githubusercontent.com/55148235/211157229-dc317be4-4d1f-4473-ac86-e7d642a73fd1.png)
![image](https://user-images.githubusercontent.com/55148235/211157252-63f0ca9f-1152-4239-8809-0a2731097e1e.png)

![image](https://user-images.githubusercontent.com/55148235/211157237-a47d3d0c-c1e7-4fab-89bc-e3b26b60a338.png)
![image](https://user-images.githubusercontent.com/55148235/211157267-5b4508a5-7ac1-4a5f-b8b5-452d9c03154f.png)

**Comment by PiKeyAr** [comment]
Hi! Thanks, and yes, I love Keroro!

Thank you for implementing the features. I was able to use the Fill Mosaic action in a level background system, and the negative scale in a character animation system. It works great, and thanks to the Fill Mosaic action I was also able to reduce the number of objects used in looping backgrounds. As for performance, I haven't been able to get the FPS to drop below 1000 on my weakest machine so far, so it seems good, at least for my purposes.
![image](https://user-images.githubusercontent.com/23312549/211551153-b3494b00-d5b4-44a0-b0e8-5ab9da6bd4ad.png)
![image](https://user-images.githubusercontent.com/23312549/211554318-f061e256-e43a-403a-9143-a1ec62f044cc.png)

If you could consider one more request (sorry for not mentioning it in the first post), it would be excellent if NeoPic could also export the original image to a PNG file, like the Surface object. It would be extremely useful in a level editor. (Context: I'm currently working on a level background editor that stores images in external files, using Surface in the actual editor and NeoPic in the previewer. Getting it all done through NeoPic would be absolutely ideal)

Thanks again!

**Comment by defisym** [comment]
Please check the latest push

![image](https://user-images.githubusercontent.com/55148235/211996082-f37ac401-7031-49e4-a2c4-af6fc4ef3aa5.png)

Note: 
  - save is a wrapper of get surface pointer, so the behaviour is the same: fileName & key are ignored for display object and return it's display surface directly, and lib object will try to load it first if not exist.
  - file format is set by save file name's extension, e.g., `FileName.png` will save as png but FileName.jpg` is jpg. if no valid extension then it's saved as jpg by default.

**Comment by PiKeyAr** [comment]
I tried it, and it worked! Thanks a lot, this is perfect!
