### ISSUE TITLE
NeoPic negative zoom not working or crashing

### ISSUE THREAD

**Issue by PiKeyAr** [defisym/OpenFusionExamples#16]
**Type of issue**
Extension bug

**Describe the bug**
Setting negative scale in the NeoPic object does not work reliably after using the `Load From File` action more than once. Sometimes setting negative scale causes application crashes. When the crash occurs, garbage data written to `Origin Size` and `Current Size` can sometimes be seen in the debugger.

**To Reproduce**
Example MFA attached: it loads the same file every 00''-30 and tries to flip the image horizontally by setting X scale to -1.

**Expected behavior**
Sprite flipped horizontally

**Screenshots**
![image](https://user-images.githubusercontent.com/23312549/222755103-d70a4fe5-b832-4f12-aa9e-e82d1dd703f2.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2

**Additional context**
Hi, it's me again! Thank you for implementing the features I requested earlier. I've been building a character animation system using NeoPic, and I have run into an issue that I think could be a bug. I have reduced the code to a single event that doesn't work reliably and can sometimes cause crashes. I would appreciate your help in resolving this issue. Here's a test MFA:
[crashtest.zip](https://github.com/defisym/OpenFusionExamples/files/10883243/crashtest.zip)

Thank you for your time.

**Comment by defisym** [comment]
Hi, please pull and check if the latest version can fix it

**Comment by PiKeyAr** [comment]
Thanks for the prompt response. I can confirm that the crash is fixed now. I'm still running into the issue with the flipping not working reliably. 

I am attaching some bits of the animation system I was working on. You can use the radio button to switch animation direction to left or right, which in turn sets the scale to -1 or 1. As new frames are loaded, the flipping takes a while to apply and sometimes the character is stuck on the wrong direction. I have mainly run into this problem in Direct3D 9 mode. The issue appears to be gone in DirectX 11 mode.
[SpriteLoader.zip](https://github.com/defisym/OpenFusionExamples/files/10884409/SpriteLoader.zip)

Is it preferable to load separate left-facing animation frames in this scenario?

Many thanks for your help

**Comment by defisym** [comment]
I think it may be a bug in DX9 runtime.
I use the following codes to flip textures:
```C++
			pFlip->Clone(*pSf);
			(pFlip->*pFlipFunc)();
```
`pFlipFunc` is a member function passed in, e.g., `&cSurface::ReverseX` and `pSf` is the source surface
for some reason, the source surface is also modified in DX9 if `pSf` is a HWA texture, convert source to bitmap before cloning and flipping should fix it.

**Comment by PiKeyAr** [comment]
Oh, I see! I will try to report this to Clickteam, maybe they will fix it. Thank you very much for looking into this, and for the workaround. It works well in the latest version of the extension.
