### ISSUE TITLE
Example Files Require WinAPI.mfx

### ISSUE THREAD

**Issue by WizenThorne** [defisym/OpenFusionExamples#61]
There is no way to install WinAPI.mfx from the extension manager but this extension is required to open FFMpeg_1080P.mfa example file.

**Comment by defisym** [comment]
https://github.com/defisym/OpenFusionExamples/tree/master/Extensions/WinAPI/ToInstall/Files
It's used to test the cache function when reaching the memory limit by loading all files under given path.
Built-in list object won't load subfolders recursively so that's why this function was made.

**Comment by defisym** [comment]
Hi, hopes you have solved your issue, the info above should enough.
